# Generated by Django 5.2.7 on 2025-10-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256_hash', models.CharField(max_length=64, unique=True)),
                ('original_string', models.TextField()),
                ('length', models.IntegerField()),
                ('is_palindrome', models.BooleanField()),
                ('unique_characters', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('character_frequency_map', models.JSONField()),
            ],
        ),
    ]
