# Generated by Django 5.2.7 on 2025-10-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='String',
            new_name='AnalyzedString',
        ),
    ]
