# Generated by Django 5.2.7 on 2025-10-21 21:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_rename_string_analyzedstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedstring',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
