# Generated by Django 5.2.7 on 2025-10-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_analyzedstring_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedstring',
            name='created_at',
            field=models.DateTimeField(default='2025-10-21T21:45:41Z'),
        ),
    ]
